### ISSUE TITLE
(Request) Combat Only filter

### ISSUE THREAD

**Issue by Nillinn** [Pythyu/WhereIsMyMouse#10]
A setting that only enables the plugin's functionality while in combat.

**Comment by Pythyu** [comment]
Nice idea I'll look into it :)

**Comment by Pythyu** [comment]
Done in [1dea369033d52db27ad82505518edb37cd0580c0](https://github.com/Pythyu/WhereIsMyMouse/commit/1dea369033d52db27ad82505518edb37cd0580c0)
