### ISSUE TITLE
Dawn Trail

### ISSUE THREAD

**Issue by Cerberpupuwu** [Pythyu/WhereIsMyMouse#18]
Hey! was wondering if youd update for dawn trail ^^ love this plugin its so good for my bad eyes! thank you for your amazing hard work! ♥

**Comment by Pythyu** [comment]
Hey 👋 
Sorry for my inactivity, I have been quite busy recently. I'll try to release the update today or tomorrow 🙇

**Comment by Pythyu** [comment]
Should be updated on [testing](https://github.com/goatcorp/DalamudPluginsD17/pull/4010)

**Comment by Cerberpupuwu** [comment]
ahhh thank you so much! works perfectly!!!
